[project]
dependencies = [
    "envparse>=0.2.0",
    "aiogram>=2.22.1",
]
requires-python = ">=3.10"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
